#!/bin/sh
# lab-down.sh - Tear down all VMs and optionally clean up OVS bridge
# One command to shut down the full test lab.

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"

# ── Colors (terminal only) ──────────────────────────────────────────────
if [ -t 1 ]; then
    RED='\033[1;31m'
    GRN='\033[1;32m'
    YEL='\033[1;33m'
    CYN='\033[1;36m'
    RST='\033[0m'
else
    RED=''; GRN=''; YEL=''; CYN=''; RST=''
fi

log()   { printf "${GRN}[+]${RST} %s\n" "$*"; }
warn()  { printf "${YEL}[!]${RST} %s\n" "$*" >&2; }
err()   { printf "${RED}[-]${RST} %s\n" "$*" >&2; }
info()  { printf "${CYN}[*]${RST} %s\n" "$*"; }

# ── Usage ────────────────────────────────────────────────────────────────
usage() {
    cat <<'EOF'
Usage: lab-down.sh [OPTIONS]

Tear down all VMs and optionally clean up OVS bridge.

OPTIONS:
    --keep-bridge    Keep the OVS bridge (don't delete ovs-br0)
    --help           Show this help message

EXAMPLES:
    lab-down.sh                # Full teardown: destroy VMs + remove bridge
    lab-down.sh --keep-bridge  # Destroy VMs but keep bridge

EOF
    exit 0
}

# ── Parse arguments ──────────────────────────────────────────────────────
KEEP_BRIDGE=0

while [ $# -gt 0 ]; do
    case "$1" in
        --keep-bridge) KEEP_BRIDGE=1 ;;
        --help|-h)      usage ;;
        *) err "Unknown option: $1"; usage ;;
    esac
    shift
done

cd "$SCRIPT_DIR"

# ── Prerequisites check ───────────────────────────────────────────────────
log "Checking prerequisites..."

check_cmd() {
    if ! command -v "$1" >/dev/null 2>&1; then
        err "Required command not found: $1"
        exit 1
    fi
}

check_cmd terraform
check_cmd virsh
check_cmd ovs-vsctl

log "Prerequisites OK"

# ── Destroy VMs ───────────────────────────────────────────────────────────
log "Destroying all VMs..."

terraform destroy -auto-approve

log "VMs destroyed"

# ── Remove OVS bridge (unless --keep-bridge) ───────────────────────────────
if [ $KEEP_BRIDGE -eq 0 ]; then
    log "Removing OVS bridge..."
    
    if ovs-vsctl br-exists ovs-br0 2>/dev/null; then
        sudo ovs-vsctl del-br ovs-br0
        log "OVS bridge removed"
    else
        info "OVS bridge ovs-br0 does not exist (already removed)"
    fi
else
    info "Keeping OVS bridge (--keep-bridge)"
fi

# ── Clean up libvirt resources (if state is stale/missing) ───────────────
log "Cleaning up any stale libvirt resources..."

# Networks
for net in "netutil-lab-mgmt" "netutil-lab-ovs"; do
    if virsh -c qemu:///system net-info "$net" >/dev/null 2>&1; then
        info "Destroying network: $net"
        virsh -c qemu:///system net-destroy "$net" 2>/dev/null || true
        virsh -c qemu:///system net-undefine "$net" 2>/dev/null || true
    fi
done

# Storage pool
for pool in "netutil-lab-volumes" "netutil-lab-pool"; do
    if virsh -c qemu:///system pool-info "$pool" >/dev/null 2>&1; then
        info "Destroying storage pool: $pool"
        virsh -c qemu:///system pool-destroy "$pool" 2>/dev/null || true
        virsh -c qemu:///system pool-undefine "$pool" 2>/dev/null || true
    fi
done

# Domains (VMs)
for domain in "netutil-lab-debian" "netutil-lab-dmz" "netutil-lab-kali" "netutil-lab-ubuntu" "netutil-lab-windows" "netutil-lab-cisco-ios" "netutil-lab-cisco-nexus"; do
    if virsh -c qemu:///system dominfo "$domain" >/dev/null 2>&1; then
        info "Undefining domain: $domain"
        # Try regular undefine first, then with --nvram for UEFI VMs
        virsh -c qemu:///system undefine "$domain" 2>/dev/null || \
        virsh -c qemu:///system undefine --nvram "$domain" 2>/dev/null || true
    fi
done

# Cloud-init ISOs (generated by Terraform)
if [ -d "$SCRIPT_DIR/images" ]; then
    info "Removing cloud-init ISOs..."
    rm -f "$SCRIPT_DIR/images/netutil-lab-"*-init.iso 2>/dev/null || true
fi

log "Libvirt resources cleaned"

# ── Done ─────────────────────────────────────────────────────────────────
log "Lab shutdown complete!"